rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
         views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/',
         views.add_page, name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    #path('search/', views.search, name='search'),
    path('goto/', views.goto_url, name='goto'),
    path('register_profile/', views.register_profile, name='register_profile'),

]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from rango import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', views.MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
class UserProfile(models.Model):
    # This line is required. Links Userprofile to a suer model instance
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #The additional attributes we wish to include
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User
import re

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form..
    class Meta:
        # Provide an association between the ModelForm and a model..
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.",
                            widget= forms.TextInput(attrs={'class':'form-control'}))
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.",
                         widget= forms.TextInput(attrs={'class':'form-control'}))
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # Strip away any leading http or https
        url = re.sub(r"http[s]:[\/]+", "", url)

        # If url is not empty and doesn't start with 'https://',
        # then prepend 'https://' as we want to make sure
        # we are accessing a secure site
        if url:
            url = f'https://{url}'
            cleaned_data['url'] = url

        return cleaned_data

    class Meta:
        # Provide an association between the ModelForm and a model..
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field).
        #fields = ('title', 'url', 'views').
    
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website','picture',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category, Page
from rango.forms import CategoryForm
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
import json
from serpapi import GoogleSearch
from rango.search import run_query
from registration.backends.simple.views import RegistrationView

def index(request):
    # Query the database for a list of ALL categories currently stored.
    # Order the categories by the number of likes in descending order.
    # Retrieve the top 5 only -- or all if less than 5.
    category_list = Category.objects.order_by('-likes')[:5]
    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    page_list = Page.objects.order_by('-views')[:5]

    # Construct a dictionary to pass to the template engine as
    # its context. Note the key boldmessage matches to
    # {{ aboldmessage }} in the template!
    context_dict = {}
    #context_dict = {'aboldmessage': 'Crunchy, creamy, cookie, candy, cupcake!'}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    # Place the list of categories in our context_dict dictionary (with our boldmessage!)
    # that will be passed to the template engine.
    context_dict['categories'] = category_list
    # Place the list of pages in our context_dict dictionary (with our boldmessage!)
    # that will be passed to the template engine.
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)
    # context_dict['visits'] = int(request.COOKIES.get('visits', '1'))
    # context_dict['visits'] = get_server_side_cookie(request, 'visits', 1)
    # request.session.set_test_cookie()

    # return render(request, 'rango/index.html', context=context_dict)

    # Obtain our Response object early so we can add cookie information.
    response = render(request, 'rango/index.html', context=context_dict)
    # Call the helper function to handle the cookies
    # response = visitor_cookie_handler(request, response)
    # Return response back to the user, updating any cookies that need changed.
    return response

def about(request):
    context_dict = {'aboutmessage': 'This tutorial has been put together by Martin Rodriguez'}

    #if request.session.test_cookie_worked():
        #print("TEST COOKIE WORKED!")
        #request.session.delete_test_cookie()
    
    visitor_cookie_handler(request)
    # context_dict['visits'] = int(request.COOKIES.get('visits', '1'))
    context_dict['visits'] = get_server_side_cookie(request, 'visits', 1)
    

    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
    #vCreate a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}

    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category).order_by('-views')

        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category

    except Category.DoesNotExist:

        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None

     # Start new search functionality code.
    context_dict['query'] = 'search'
    if request.method == 'POST':
        query = request.POST['query'].strip()
            
        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query
	# End new search functionality code.
    
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():

            # Save the new category to the database.
            form.save(commit=True)

            # Now that the category is saved, we could confirm this.
            # For now, just redirect the user back to the index view.
            return redirect('/rango/')
        
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)

    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    return render(request, 'rango/add_category.html', {'form':form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    if category is None:
        return redirect(reverse('rango:index'))
    
    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.view = 0
                page.save()

                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug': category_name_slug}))
            else:
                print(form.errors)

    context_dict = {'form' : form, 'category':category}
    return render(request, 'rango/add_page.html', context=context_dict)

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

# Use the login_required() decorator to ensure only those logged in can
# access the view.
'''
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))
'''

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    # Get the number of visits to the site.
    # We use the COOKIES.get() function to obtain the visits cookie.
    # If the cookie exists, the value returned is casted to an integer.
    # If the cookie doesn't exist, then the default value of 1 is used.
    # visits = int(request.COOKIES.get('visits', '1'))
    visits = int(get_server_side_cookie(request, 'visits', '1'))    # last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
    last_visit_cookie = get_server_side_cookie(request,'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')    
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        # response.set_cookie('last_visit', str(datetime.now()))
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        # response.set_cookie('last_visit', last_visit_cookie)
        request.session['last_visit'] = last_visit_cookie

    # Update/set the visits cookie
    # response.set_cookie('visits', visits)
    # return response
    request.session['visits'] = visits

'''
def search(request):
    result_list = []
    query = ''
    
    if request.method == 'POST':
        query = request.POST['query'].strip()
        
        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'query':query, 'result_list': result_list})
'''
    
def goto_url(request):
    if request.method == 'GET':
        page_id = request.GET.get('page_id')
        try:
            selected_page = Page.objects.get(id=page_id)
            selected_page.views = selected_page.views + 1
            selected_page.save()
            return redirect(selected_page.url)
        except Page.DoesNotExist:
            return redirect(reverse('rango:index'))
    return redirect(reverse('rango:index'))

@login_required
def register_profile(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
    context_dict = {'form': form}
    return render(request, 'rango/profile_registration.html', context_dict)

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    About
{% endblock title_block %}

{% block body_block %}
<h1>Rango says....</h1>
<div>
    <p>Welcome this is the Rango's about page</p>
    <strong>{{ aboutmessage }}</strong>
</div>
<div>
    <img src="{% static 'images/rango.png' %}" alt="Rango image"> <br/>
    <img src="{% get_media_prefix %}rango2.png" alt="Rango2 image"> <br/>
    <img src="{{ MEDIA_URL }}rango3.png" alt="Rango3 image">
</div>

<p>Visits: {{ visits }}</p>

{% endblock body_block %}

rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
Add Category
{% endblock title_block %}

{% block body_block %}
<div class="container-fluid py-3">
    <div class="row bg-light rounded-3">
        <h1 class="display-5 fw-bold">Add Category</h1>
    </div>
    <div class="row py-5">
        <div class="col-md-6">
            <form id="category_form" method="post" action="{% url 'rango:add_category' category.slug %}">
            {% csrf_token %}
                <div class="form-floating">
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}
                        {{ field }}<br/>
                    {% endfor %}
                </div>
            <button class="btn btn-lg btn-primary"
            type="submit" name="submit" value="Create Category">
            Add Category</button>
            </form>
        </div>
    </div>
</div>
{% endblock body_block %}

rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
    Add a page
{% endblock title_block %}
{% block body_block %}
    <div class="container-fluid py-3">
        <div class="row bg-light rounded-3">
            <h1 class="display-5 fw-bold">Add a Page to {{ category.name }}</h1>
        </div>
        <div class="row py-5">
            <div class="col-md-6">
                <form id="add_page_form"
                      method="post"
                      action="{% url 'rango:add_page' category.slug %}">
                    {% csrf_token %}
                    <div class="form-floating">
                        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                        {% for field in form.visible_fields %}
                            {{ field.errors }}
                            {{ field.help_text }}
                            {{ field }}
                            <br />
                        {% endfor %}
                    </div>
                    <button class="btn btn-lg btn-primary"
                            type="submit"
                            name="submit"
                            value="Add Page">Add Page</button>
                </form>
            </div>
        </div>
    </div>
{% endblock body_block %}

rango/templates/rango/base-old.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock title_block %}
    </title>
</head>
<body>
    <div>
        {% block body_block %} 
        {% endblock body_block %}
    </div>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
    <hr>
    <div>
        <ul>
            {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index'%}">Logout</a></li>
                <li><a href="{% url 'auth_password_change' %}">Password change</a></li>
                <li><a href="{% url 'auth_password_change_done' %}">Change complete</a></li>    
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
            {% else %}
                <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>

            {% endif %}
                <!-- Outside the conditional statements, ALWAYS show -->
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
    
</body>
</html>

rango/templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>
      {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    <link rel="canonical"
          href="https://getbootstrap.com/docs/5.3/examples/dashboard/">
    <!--link href="https://getbootstrap.com/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"-->
    <link href="https://getbootstrap.com/docs/5.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <!-- Favicons -->
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <meta name="theme-color" content="#712cf9">
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.comddocs/5.3/dashboard.css"
          rel="stylesheet">
  </head>
  <body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6"
         href="{% url 'rango:index' %}">Rango</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#sidebarMenu"
              aria-controls="sidebarMenu"
              aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-nav">
        <div class="nav-item text-nowrap">
          <ul>
            {% if user.is_authenticated %}
              <!-- Show these links when the user is logged in -->
              <a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a>
            {% else %}
              <!-- Show these links when the user is NOT logged in -->
              <a href="{% url 'registration_register' %}">Sign Up</a>
              <a href="{% url 'auth_login' %}">Login</a>
            {% endif %}
          </ul>
        </div>
      </div>
    </header>
    <div class="container-fluid">
      <div class="row">
        <nav id="sidebarMenu"
             class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="position-sticky pt-3 sidebar-sticky">
            
            {% block sidebar_block %}
              <ul class="nav flex-column mb-2">
                <li class="nav-item">
                  <a class="nav-link" href="{% get_category_list category %}">
                    <span data-feather="file-text" class="align-text-bottom"></span>
                  </a>
                </li>
              </ul>
            {% endblock sidebar_block %}
         
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
              <span>Links</span>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:add_category' %}">
                  <span data-feather="file-text" class="align-text-bottom"></span>
                  Add New Category
                </a>
              </li>
              {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'rango:restricted' %}">
                    <span data-feather="file-text" class="align-text-bottom"></span>
                    Restricted Page
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth_password_change' %}">
                    <span data-feather="file-text" class="align-text-bottom"></span>
                  Change Password</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'rango:about' %}">
                    <span data-feather="file-text" class="align-text-bottom"></span>
                  About</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </nav>
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <!--        <h1 class="h2">Dashboard</h1>  -->
            {% block body_block %}{% endblock %}
          </div>
        </main>
      </div>
    </div>
    <footer>
      <p class="float-right">
        <a href="#">Back to top</a>
      </p>
      <p>&copy; 2023 Tango With Django 4 &middot;</p>
    </footer>
    <!--script src="https://getbootstrap.com/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script -->
    <!--script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></script -->
    <!--script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script -->
    <script src="https://getbootstrap.com/docs/5.3/dist/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
            crossorigin="anonymous"></script>
    <script src="https://getbootstrap.com/dashboard.js"></script>
  </body>
</html>

rango/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}
{% block body_block %}
<div class="container-fluid py-3">
    {% if category %}
    <div class="row bg-light rounded-3">
        <h1 class="display-5 fw-bold">{{ category.name }}</h1>
    </div>
    <div>
        <strong id="like_count">{{ category.likes }}</strong> likes
        {% if user.is_authenticated %}
        <button id="like_btn"
         data-categoryid="{{ category.id }}"
          class="btn btn-primary btn-sm"
          type="button">
        <span data-feather="thumbs-up"></span>
         Like Category
        </button>
        {% endif %}
       </div>


       {% if pages %}
       <ul>
        {% for page in pages %}
           <li>
            <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
             {% if page.views > 1 %}
           ({{ page.views }} views)
             {% elif page.views == 1 %}
              ({{ page.views }} view)
             {% endif %}
        </li>
           {% endfor %}
       </ul>
       {% else %}
           <strong>No pages currently in category.</strong>
       {% endif %}

   <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
    {% else %}
    The specified category does not exist.
    {% endif %}
    {% if user.is_authenticated %}
    <div class="row py-5">
        <form class="row g-3" id="user-form" method="post" action="{% url 'rango:show_category' category.slug %}">
            {% csrf_token %}
            <div class="col-auto">
                <label class="visually-hidden">Search</label>
                <input type="text" readonly class="form-control-plaintext" value="Enter your search terms">
            </div>
            <div class="col-auto">
                <label class="visually-hidden">Search</label>
                <input type="text" class="form-control" id="query" placeholder="{{ query }}" name="query">
            </div>
            <div class="col-auto">
                <button type="submit" name="submit" class="btn btn-primary mb-3">Search</button>
            </div>
        </form>
    </div>
    <div class="row py-5">
        {% if result_list %}
        <h2>Results</h2>
        <div class="list-group">
            {% for result in result_list %}
            <div class="list-group-item">
                <h3 class="list-group-item-heading">
                    <a href="{{ result.link }}">
                        {{ result.title|safe|escape }}
                    </a>
                </h3>
                <p class="list-group-item-text">
                    {{ result.snippet|safe|escape }}
                </p>
                <button class="btn btn-info btn-sm rango-page-add"
                type="button"
                data-categoryid="{{ category.id }}"
                data-title="{{ result.title }}"
                data-url="{{ result.link }}">
                Add
              </button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    {% endif %}

{% endblock %}

rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
    Homepage
{% endblock title_block %}
{% block body_block %}
    <div>
        <div class="container-fluid py-6 pt-6 pb-6 pr-6">
            <div class="row bg-light rounded-3">
                <h1 class="display-5 fw-bold">Rango says...</h1>
                <p class="col-md-8 fs-4">
                    {% if user.is_authenticated %}
                        howdy {{ user.username }}!
                    {% else %}
                        hey there partner!
                    {% endif %}
                </p>
                <strong>{{ aboldmessage }}</strong>
            </div>
            
            <div class="row py-4">
                <div class="col-md-6">
                    <div class="h-100 p-5 bg-light rounded-3">
                        <h2>Most Liked Categories</h2>
                        {% if categories %}
                            <ul class="list-group">
                                {% for category in categories %}
                                    <li class="list-group-item">
                                        <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <strong>There are no categories present.</strong>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="h-100 p-5 bg-light rounded-3">
                        <h2>Most Viewed Pages</h2>
                        {% if pages %}
                            <ul class="list-group">
                                {% for page in pages %}
                                    <li class="list-group-item">
                                        <a href="{{ page.url }}">{{ page.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <strong>There are no pages present.</strong>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div>
                <img src="{% static 'images/rango.png' %}" alt="Picture of Rango">
            </div>
            <hr>
            <div>
                <a href="{% url 'rango:about' %}">About</a>
                <br />
                <a href="/rango/add_category/">Add a New Category</a>
                <br />
            </div>
        </div>
    </div>
{% endblock body_block %}